from . import battery
from . import bluetooth
from . import dunst
from . import monitor
from . import mullvad
from . import music
from . import network
from . import sway
from . import systemd
from . import volume
from . import top
from . import transmission
